[project]
name = "online-product-tracker"
version = "0.1.0"
description = "Online Product Tracker"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "types-requests>=2.32.0.20250328",
]
